//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 09:46:47 PM CET 
//


package hu.groupama.portal.product.biztositas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for adat_Szerződés complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adat_Szerződés">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Törlendő" type="{}típus_IgenNem"/>
 *         &lt;element name="Számla_sorszáma" type="{}típus_Kötelező"/>
 *         &lt;element name="Vásárlás_dátuma" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Vásárló">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Név" type="{}típus_Kötelező"/>
 *                   &lt;element name="Lakcím" type="{}blokk_Cím"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Vagyontárgy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Cikk_kód" type="{}típus_Kötelező"/>
 *                   &lt;element name="Kategória" type="{}típus_Kötelező"/>
 *                   &lt;element name="Márka" type="{}típus_Kötelező"/>
 *                   &lt;element name="Típus" type="{}típus_Kötelező"/>
 *                   &lt;element name="Gyártói_garancia_hossza" type="{}típus_Tartam"/>
 *                   &lt;element name="Nagykereskedelmi_ár" type="{}típus_Ft"/>
 *                   &lt;element name="Fogyasztói_ár" type="{}típus_Ft"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Biztosítás">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Teljes_tartam" type="{}típus_Tartam"/>
 *                   &lt;element name="Biztosítási_díj" type="{}típus_Ft"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Áruház">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Kód" type="{}típus_Kötelező"/>
 *                   &lt;element name="Név" type="{}típus_Kötelező"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adat_Szerz\u0151d\u00e9s", propOrder = {
    "t\u00f6rlend\u0151",
    "sz\u00e1mlaSorsz\u00e1ma",
    "v\u00e1s\u00e1rl\u00e1sD\u00e1tuma",
    "v\u00e1s\u00e1rl\u00f3",
    "vagyont\u00e1rgy",
    "biztos\u00edt\u00e1s",
    "\u00e1ruh\u00e1z"
})
public class AdatSzerződés {

    @XmlElement(name = "T\u00f6rlend\u0151", required = true)
    protected String törlendő;
    @XmlElement(name = "Sz\u00e1mla_sorsz\u00e1ma", required = true)
    protected String számlaSorszáma;
    @XmlElement(name = "V\u00e1s\u00e1rl\u00e1s_d\u00e1tuma", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vásárlásDátuma;
    @XmlElement(name = "V\u00e1s\u00e1rl\u00f3", required = true)
    protected AdatSzerződés.Vásárló vásárló;
    @XmlElement(name = "Vagyont\u00e1rgy", required = true)
    protected AdatSzerződés.Vagyontárgy vagyontárgy;
    @XmlElement(name = "Biztos\u00edt\u00e1s", required = true)
    protected AdatSzerződés.Biztosítás biztosítás;
    @XmlElement(name = "\u00c1ruh\u00e1z", required = true)
    protected AdatSzerződés.Áruház áruház;

    /**
     * Gets the value of the törlendő property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTörlendő() {
        return törlendő;
    }

    /**
     * Sets the value of the törlendő property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTörlendő(String value) {
        this.törlendő = value;
    }

    /**
     * Gets the value of the számlaSorszáma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSzámlaSorszáma() {
        return számlaSorszáma;
    }

    /**
     * Sets the value of the számlaSorszáma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSzámlaSorszáma(String value) {
        this.számlaSorszáma = value;
    }

    /**
     * Gets the value of the vásárlásDátuma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVásárlásDátuma() {
        return vásárlásDátuma;
    }

    /**
     * Sets the value of the vásárlásDátuma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVásárlásDátuma(XMLGregorianCalendar value) {
        this.vásárlásDátuma = value;
    }

    /**
     * Gets the value of the vásárló property.
     * 
     * @return
     *     possible object is
     *     {@link AdatSzerződés.Vásárló }
     *     
     */
    public AdatSzerződés.Vásárló getVásárló() {
        return vásárló;
    }

    /**
     * Sets the value of the vásárló property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdatSzerződés.Vásárló }
     *     
     */
    public void setVásárló(AdatSzerződés.Vásárló value) {
        this.vásárló = value;
    }

    /**
     * Gets the value of the vagyontárgy property.
     * 
     * @return
     *     possible object is
     *     {@link AdatSzerződés.Vagyontárgy }
     *     
     */
    public AdatSzerződés.Vagyontárgy getVagyontárgy() {
        return vagyontárgy;
    }

    /**
     * Sets the value of the vagyontárgy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdatSzerződés.Vagyontárgy }
     *     
     */
    public void setVagyontárgy(AdatSzerződés.Vagyontárgy value) {
        this.vagyontárgy = value;
    }

    /**
     * Gets the value of the biztosítás property.
     * 
     * @return
     *     possible object is
     *     {@link AdatSzerződés.Biztosítás }
     *     
     */
    public AdatSzerződés.Biztosítás getBiztosítás() {
        return biztosítás;
    }

    /**
     * Sets the value of the biztosítás property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdatSzerződés.Biztosítás }
     *     
     */
    public void setBiztosítás(AdatSzerződés.Biztosítás value) {
        this.biztosítás = value;
    }

    /**
     * Gets the value of the áruház property.
     * 
     * @return
     *     possible object is
     *     {@link AdatSzerződés.Áruház }
     *     
     */
    public AdatSzerződés.Áruház getÁruház() {
        return áruház;
    }

    /**
     * Sets the value of the áruház property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdatSzerződés.Áruház }
     *     
     */
    public void setÁruház(AdatSzerződés.Áruház value) {
        this.áruház = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Teljes_tartam" type="{}típus_Tartam"/>
     *         &lt;element name="Biztosítási_díj" type="{}típus_Ft"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "teljesTartam",
        "biztos\u00edt\u00e1siD\u00edj"
    })
    public static class Biztosítás {

        @XmlElement(name = "Teljes_tartam")
        protected int teljesTartam;
        @XmlElement(name = "Biztos\u00edt\u00e1si_d\u00edj")
        protected int biztosításiDíj;

        /**
         * Gets the value of the teljesTartam property.
         * 
         */
        public int getTeljesTartam() {
            return teljesTartam;
        }

        /**
         * Sets the value of the teljesTartam property.
         * 
         */
        public void setTeljesTartam(int value) {
            this.teljesTartam = value;
        }

        /**
         * Gets the value of the biztosításiDíj property.
         * 
         */
        public int getBiztosításiDíj() {
            return biztosításiDíj;
        }

        /**
         * Sets the value of the biztosításiDíj property.
         * 
         */
        public void setBiztosításiDíj(int value) {
            this.biztosításiDíj = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Cikk_kód" type="{}típus_Kötelező"/>
     *         &lt;element name="Kategória" type="{}típus_Kötelező"/>
     *         &lt;element name="Márka" type="{}típus_Kötelező"/>
     *         &lt;element name="Típus" type="{}típus_Kötelező"/>
     *         &lt;element name="Gyártói_garancia_hossza" type="{}típus_Tartam"/>
     *         &lt;element name="Nagykereskedelmi_ár" type="{}típus_Ft"/>
     *         &lt;element name="Fogyasztói_ár" type="{}típus_Ft"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cikkK\u00f3d",
        "kateg\u00f3ria",
        "m\u00e1rka",
        "t\u00edpus",
        "gy\u00e1rt\u00f3iGaranciaHossza",
        "nagykereskedelmi\u00c1r",
        "fogyaszt\u00f3i\u00c1r"
    })
    public static class Vagyontárgy {

        @XmlElement(name = "Cikk_k\u00f3d", required = true)
        protected String cikkKód;
        @XmlElement(name = "Kateg\u00f3ria", required = true)
        protected String kategória;
        @XmlElement(name = "M\u00e1rka", required = true)
        protected String márka;
        @XmlElement(name = "T\u00edpus", required = true)
        protected String típus;
        @XmlElement(name = "Gy\u00e1rt\u00f3i_garancia_hossza")
        protected int gyártóiGaranciaHossza;
        @XmlElement(name = "Nagykereskedelmi_\u00e1r")
        protected int nagykereskedelmiÁr;
        @XmlElement(name = "Fogyaszt\u00f3i_\u00e1r")
        protected int fogyasztóiÁr;

        /**
         * Gets the value of the cikkKód property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCikkKód() {
            return cikkKód;
        }

        /**
         * Sets the value of the cikkKód property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCikkKód(String value) {
            this.cikkKód = value;
        }

        /**
         * Gets the value of the kategória property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKategória() {
            return kategória;
        }

        /**
         * Sets the value of the kategória property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKategória(String value) {
            this.kategória = value;
        }

        /**
         * Gets the value of the márka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMárka() {
            return márka;
        }

        /**
         * Sets the value of the márka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMárka(String value) {
            this.márka = value;
        }

        /**
         * Gets the value of the típus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTípus() {
            return típus;
        }

        /**
         * Sets the value of the típus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTípus(String value) {
            this.típus = value;
        }

        /**
         * Gets the value of the gyártóiGaranciaHossza property.
         * 
         */
        public int getGyártóiGaranciaHossza() {
            return gyártóiGaranciaHossza;
        }

        /**
         * Sets the value of the gyártóiGaranciaHossza property.
         * 
         */
        public void setGyártóiGaranciaHossza(int value) {
            this.gyártóiGaranciaHossza = value;
        }

        /**
         * Gets the value of the nagykereskedelmiÁr property.
         * 
         */
        public int getNagykereskedelmiÁr() {
            return nagykereskedelmiÁr;
        }

        /**
         * Sets the value of the nagykereskedelmiÁr property.
         * 
         */
        public void setNagykereskedelmiÁr(int value) {
            this.nagykereskedelmiÁr = value;
        }

        /**
         * Gets the value of the fogyasztóiÁr property.
         * 
         */
        public int getFogyasztóiÁr() {
            return fogyasztóiÁr;
        }

        /**
         * Sets the value of the fogyasztóiÁr property.
         * 
         */
        public void setFogyasztóiÁr(int value) {
            this.fogyasztóiÁr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Név" type="{}típus_Kötelező"/>
     *         &lt;element name="Lakcím" type="{}blokk_Cím"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "n\u00e9v",
        "lakc\u00edm"
    })
    public static class Vásárló {

        @XmlElement(name = "N\u00e9v", required = true)
        protected String név;
        @XmlElement(name = "Lakc\u00edm", required = true)
        protected BlokkCím lakcím;

        /**
         * Gets the value of the név property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNév() {
            return név;
        }

        /**
         * Sets the value of the név property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNév(String value) {
            this.név = value;
        }

        /**
         * Gets the value of the lakcím property.
         * 
         * @return
         *     possible object is
         *     {@link BlokkCím }
         *     
         */
        public BlokkCím getLakcím() {
            return lakcím;
        }

        /**
         * Sets the value of the lakcím property.
         * 
         * @param value
         *     allowed object is
         *     {@link BlokkCím }
         *     
         */
        public void setLakcím(BlokkCím value) {
            this.lakcím = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Kód" type="{}típus_Kötelező"/>
     *         &lt;element name="Név" type="{}típus_Kötelező"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "k\u00f3d",
        "n\u00e9v"
    })
    public static class Áruház {

        @XmlElement(name = "K\u00f3d", required = true)
        protected String kód;
        @XmlElement(name = "N\u00e9v", required = true)
        protected String név;

        /**
         * Gets the value of the kód property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKód() {
            return kód;
        }

        /**
         * Sets the value of the kód property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKód(String value) {
            this.kód = value;
        }

        /**
         * Gets the value of the név property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNév() {
            return név;
        }

        /**
         * Sets the value of the név property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNév(String value) {
            this.név = value;
        }

    }

}
