//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 09:46:47 PM CET 
//


package hu.groupama.portal.product.biztositas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Termékgarancia">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Felhasználó" type="{}adat_Felhasználó"/>
 *                   &lt;element name="Szerződés" type="{}adat_Szerződés"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Eredmény" type="{}adat_Eredmény"/>
 *         &lt;element name="Hiba" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "term\u00e9kgarancia",
    "eredm\u00e9ny",
    "hiba"
})
@XmlRootElement(name = "Biztos\u00edt\u00e1s")
public class Biztosítás {

    @XmlElement(name = "Term\u00e9kgarancia")
    protected Biztosítás.Termékgarancia termékgarancia;
    @XmlElement(name = "Eredm\u00e9ny")
    protected AdatEredmény eredmény;
    @XmlElement(name = "Hiba")
    protected String hiba;

    /**
     * Gets the value of the termékgarancia property.
     * 
     * @return
     *     possible object is
     *     {@link Biztosítás.Termékgarancia }
     *     
     */
    public Biztosítás.Termékgarancia getTermékgarancia() {
        return termékgarancia;
    }

    /**
     * Sets the value of the termékgarancia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Biztosítás.Termékgarancia }
     *     
     */
    public void setTermékgarancia(Biztosítás.Termékgarancia value) {
        this.termékgarancia = value;
    }

    /**
     * Gets the value of the eredmény property.
     * 
     * @return
     *     possible object is
     *     {@link AdatEredmény }
     *     
     */
    public AdatEredmény getEredmény() {
        return eredmény;
    }

    /**
     * Sets the value of the eredmény property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdatEredmény }
     *     
     */
    public void setEredmény(AdatEredmény value) {
        this.eredmény = value;
    }

    /**
     * Gets the value of the hiba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHiba() {
        return hiba;
    }

    /**
     * Sets the value of the hiba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHiba(String value) {
        this.hiba = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Felhasználó" type="{}adat_Felhasználó"/>
     *         &lt;element name="Szerződés" type="{}adat_Szerződés"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "felhaszn\u00e1l\u00f3",
        "szerz\u0151d\u00e9s"
    })
    public static class Termékgarancia {

        @XmlElement(name = "Felhaszn\u00e1l\u00f3", required = true)
        protected AdatFelhasználó felhasználó;
        @XmlElement(name = "Szerz\u0151d\u00e9s", required = true)
        protected AdatSzerződés szerződés;

        /**
         * Gets the value of the felhasználó property.
         * 
         * @return
         *     possible object is
         *     {@link AdatFelhasználó }
         *     
         */
        public AdatFelhasználó getFelhasználó() {
            return felhasználó;
        }

        /**
         * Sets the value of the felhasználó property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdatFelhasználó }
         *     
         */
        public void setFelhasználó(AdatFelhasználó value) {
            this.felhasználó = value;
        }

        /**
         * Gets the value of the szerződés property.
         * 
         * @return
         *     possible object is
         *     {@link AdatSzerződés }
         *     
         */
        public AdatSzerződés getSzerződés() {
            return szerződés;
        }

        /**
         * Sets the value of the szerződés property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdatSzerződés }
         *     
         */
        public void setSzerződés(AdatSzerződés value) {
            this.szerződés = value;
        }

    }

}
