//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 09:46:47 PM CET 
//


package hu.groupama.portal.product.biztositas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for blokk_Cím complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="blokk_Cím">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Irányítószám" type="{}típus_NemKötelező"/>
 *         &lt;element name="Település" type="{}típus_Kötelező"/>
 *         &lt;element name="Utca_házszám_emelet_ajtó" type="{}típus_Kötelező"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "blokk_C\u00edm", propOrder = {
    "ir\u00e1ny\u00edt\u00f3sz\u00e1m",
    "telep\u00fcl\u00e9s",
    "utcaH\u00e1zsz\u00e1mEmeletAjt\u00f3"
})
public class BlokkCím {

    @XmlElement(name = "Ir\u00e1ny\u00edt\u00f3sz\u00e1m", required = true)
    protected String irányítószám;
    @XmlElement(name = "Telep\u00fcl\u00e9s", required = true)
    protected String település;
    @XmlElement(name = "Utca_h\u00e1zsz\u00e1m_emelet_ajt\u00f3", required = true)
    protected String utcaHázszámEmeletAjtó;

    /**
     * Gets the value of the irányítószám property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrányítószám() {
        return irányítószám;
    }

    /**
     * Sets the value of the irányítószám property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrányítószám(String value) {
        this.irányítószám = value;
    }

    /**
     * Gets the value of the település property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelepülés() {
        return település;
    }

    /**
     * Sets the value of the település property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelepülés(String value) {
        this.település = value;
    }

    /**
     * Gets the value of the utcaHázszámEmeletAjtó property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtcaHázszámEmeletAjtó() {
        return utcaHázszámEmeletAjtó;
    }

    /**
     * Sets the value of the utcaHázszámEmeletAjtó property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtcaHázszámEmeletAjtó(String value) {
        this.utcaHázszámEmeletAjtó = value;
    }

}
