//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 09:46:47 PM CET 
//


package hu.groupama.portal.product.biztositas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.groupama.portal.product.biztositas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.groupama.portal.product.biztositas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link hu.groupama.portal.product.biztositas.Biztosítás }
     * 
     */
    public hu.groupama.portal.product.biztositas.Biztosítás createBiztosítás() {
        return new hu.groupama.portal.product.biztositas.Biztosítás();
    }

    /**
     * Create an instance of {@link AdatSzerződés }
     * 
     */
    public AdatSzerződés createAdatSzerződés() {
        return new AdatSzerződés();
    }

    /**
     * Create an instance of {@link hu.groupama.portal.product.biztositas.Biztosítás.Termékgarancia }
     * 
     */
    public hu.groupama.portal.product.biztositas.Biztosítás.Termékgarancia createBiztosításTermékgarancia() {
        return new hu.groupama.portal.product.biztositas.Biztosítás.Termékgarancia();
    }

    /**
     * Create an instance of {@link AdatEredmény }
     * 
     */
    public AdatEredmény createAdatEredmény() {
        return new AdatEredmény();
    }

    /**
     * Create an instance of {@link BlokkCím }
     * 
     */
    public BlokkCím createBlokkCím() {
        return new BlokkCím();
    }

    /**
     * Create an instance of {@link AdatFelhasználó }
     * 
     */
    public AdatFelhasználó createAdatFelhasználó() {
        return new AdatFelhasználó();
    }

    /**
     * Create an instance of {@link AdatSzerződés.Vásárló }
     * 
     */
    public AdatSzerződés.Vásárló createAdatSzerződésVásárló() {
        return new AdatSzerződés.Vásárló();
    }

    /**
     * Create an instance of {@link AdatSzerződés.Vagyontárgy }
     * 
     */
    public AdatSzerződés.Vagyontárgy createAdatSzerződésVagyontárgy() {
        return new AdatSzerződés.Vagyontárgy();
    }

    /**
     * Create an instance of {@link AdatSzerződés.Biztosítás }
     * 
     */
    public AdatSzerződés.Biztosítás createAdatSzerződésBiztosítás() {
        return new AdatSzerződés.Biztosítás();
    }

    /**
     * Create an instance of {@link AdatSzerződés.Áruház }
     * 
     */
    public AdatSzerződés.Áruház createAdatSzerződésÁruház() {
        return new AdatSzerződés.Áruház();
    }

}
