//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//


package hu.groupama.portal.product.log;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adat_Felhasználó complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adat_Felhasználó">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Azonosító" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *         &lt;element name="Piramis_törzsszám" type="{http://promarkvf.hu/ProductTypes}típus_Törzsszám"/>
 *         &lt;element name="Teszt_bejelentkezés" type="{http://promarkvf.hu/ProductTypes}típus_IgenNem"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adat_Felhaszn\u00e1l\u00f3", propOrder = {
    "azonos\u00edt\u00f3",
    "piramisT\u00f6rzssz\u00e1m",
    "tesztBejelentkez\u00e9s"
})
public class AdatFelhasználó {

    @XmlElement(name = "Azonos\u00edt\u00f3", required = true)
    protected String azonosító;
    @XmlElement(name = "Piramis_t\u00f6rzssz\u00e1m", required = true)
    protected String piramisTörzsszám;
    @XmlElement(name = "Teszt_bejelentkez\u00e9s", required = true)
    protected String tesztBejelentkezés;

    /**
     * Gets the value of the azonosító property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzonosító() {
        return azonosító;
    }

    /**
     * Sets the value of the azonosító property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzonosító(String value) {
        this.azonosító = value;
    }

    /**
     * Gets the value of the piramisTörzsszám property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiramisTörzsszám() {
        return piramisTörzsszám;
    }

    /**
     * Sets the value of the piramisTörzsszám property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiramisTörzsszám(String value) {
        this.piramisTörzsszám = value;
    }

    /**
     * Gets the value of the tesztBejelentkezés property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesztBejelentkezés() {
        return tesztBejelentkezés;
    }

    /**
     * Sets the value of the tesztBejelentkezés property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesztBejelentkezés(String value) {
        this.tesztBejelentkezés = value;
    }

}
