//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//


package hu.groupama.portal.product.log;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Biztosítás">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Termékgarancia">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Felhasználó" type="{http://promarkvf.hu/ProductWS}adat_Felhasználó"/>
 *                             &lt;element name="Szerződés">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Törlendő" type="{http://promarkvf.hu/ProductTypes}típus_IgenNem"/>
 *                                       &lt;element name="Számla_sorszáma" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *                                       &lt;element name="Vásárlás_dátuma" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="Vásárló">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Név" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *                                                 &lt;element name="Lakcím" type="{http://promarkvf.hu/ProductWS}blokk_Cím"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Vagyontárgy" type="{http://promarkvf.hu/ProductWS}Vagyontárgy"/>
 *                                       &lt;element name="Biztosítás" type="{http://promarkvf.hu/ProductWS}Biztosítás"/>
 *                                       &lt;element name="Áruház" type="{http://promarkvf.hu/ProductWS}Áruház"/>
 *                                       &lt;element name="Eredmény" type="{http://promarkvf.hu/ProductWS}adat_Eredmény"/>
 *                                       &lt;element name="Hiba" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "biztos\u00edt\u00e1s"
})
@XmlRootElement(name = "Biztos\u00edt\u00e1sok", namespace = "http://promarkvf.hu/Biztositasok")
public class Biztosítások {

    @XmlElement(name = "ID", namespace = "http://promarkvf.hu/Biztositasok")
    protected int id;
    @XmlElement(name = "Biztos\u00edt\u00e1s", namespace = "http://promarkvf.hu/Biztositasok", required = true)
    protected Biztosítások.Biztosítás biztosítás;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the biztosítás property.
     * 
     * @return
     *     possible object is
     *     {@link Biztosítások.Biztosítás }
     *     
     */
    public Biztosítások.Biztosítás getBiztosítás() {
        return biztosítás;
    }

    /**
     * Sets the value of the biztosítás property.
     * 
     * @param value
     *     allowed object is
     *     {@link Biztosítások.Biztosítás }
     *     
     */
    public void setBiztosítás(Biztosítások.Biztosítás value) {
        this.biztosítás = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Termékgarancia">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Felhasználó" type="{http://promarkvf.hu/ProductWS}adat_Felhasználó"/>
     *                   &lt;element name="Szerződés">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Törlendő" type="{http://promarkvf.hu/ProductTypes}típus_IgenNem"/>
     *                             &lt;element name="Számla_sorszáma" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
     *                             &lt;element name="Vásárlás_dátuma" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                             &lt;element name="Vásárló">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Név" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
     *                                       &lt;element name="Lakcím" type="{http://promarkvf.hu/ProductWS}blokk_Cím"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Vagyontárgy" type="{http://promarkvf.hu/ProductWS}Vagyontárgy"/>
     *                             &lt;element name="Biztosítás" type="{http://promarkvf.hu/ProductWS}Biztosítás"/>
     *                             &lt;element name="Áruház" type="{http://promarkvf.hu/ProductWS}Áruház"/>
     *                             &lt;element name="Eredmény" type="{http://promarkvf.hu/ProductWS}adat_Eredmény"/>
     *                             &lt;element name="Hiba" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "term\u00e9kgarancia"
    })
    public static class Biztosítás {

        @XmlElement(name = "Term\u00e9kgarancia", namespace = "http://promarkvf.hu/Biztositasok")
        protected Biztosítások.Biztosítás.Termékgarancia termékgarancia;

        /**
         * Gets the value of the termékgarancia property.
         * 
         * @return
         *     possible object is
         *     {@link Biztosítások.Biztosítás.Termékgarancia }
         *     
         */
        public Biztosítások.Biztosítás.Termékgarancia getTermékgarancia() {
            return termékgarancia;
        }

        /**
         * Sets the value of the termékgarancia property.
         * 
         * @param value
         *     allowed object is
         *     {@link Biztosítások.Biztosítás.Termékgarancia }
         *     
         */
        public void setTermékgarancia(Biztosítások.Biztosítás.Termékgarancia value) {
            this.termékgarancia = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Felhasználó" type="{http://promarkvf.hu/ProductWS}adat_Felhasználó"/>
         *         &lt;element name="Szerződés">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Törlendő" type="{http://promarkvf.hu/ProductTypes}típus_IgenNem"/>
         *                   &lt;element name="Számla_sorszáma" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
         *                   &lt;element name="Vásárlás_dátuma" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *                   &lt;element name="Vásárló">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Név" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
         *                             &lt;element name="Lakcím" type="{http://promarkvf.hu/ProductWS}blokk_Cím"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Vagyontárgy" type="{http://promarkvf.hu/ProductWS}Vagyontárgy"/>
         *                   &lt;element name="Biztosítás" type="{http://promarkvf.hu/ProductWS}Biztosítás"/>
         *                   &lt;element name="Áruház" type="{http://promarkvf.hu/ProductWS}Áruház"/>
         *                   &lt;element name="Eredmény" type="{http://promarkvf.hu/ProductWS}adat_Eredmény"/>
         *                   &lt;element name="Hiba" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "felhaszn\u00e1l\u00f3",
            "szerz\u0151d\u00e9s"
        })
        public static class Termékgarancia {

            @XmlElement(name = "Felhaszn\u00e1l\u00f3", namespace = "http://promarkvf.hu/Biztositasok", required = true)
            protected AdatFelhasználó felhasználó;
            @XmlElement(name = "Szerz\u0151d\u00e9s", namespace = "http://promarkvf.hu/Biztositasok", required = true)
            protected Biztosítások.Biztosítás.Termékgarancia.Szerződés szerződés;

            /**
             * Gets the value of the felhasználó property.
             * 
             * @return
             *     possible object is
             *     {@link AdatFelhasználó }
             *     
             */
            public AdatFelhasználó getFelhasználó() {
                return felhasználó;
            }

            /**
             * Sets the value of the felhasználó property.
             * 
             * @param value
             *     allowed object is
             *     {@link AdatFelhasználó }
             *     
             */
            public void setFelhasználó(AdatFelhasználó value) {
                this.felhasználó = value;
            }

            /**
             * Gets the value of the szerződés property.
             * 
             * @return
             *     possible object is
             *     {@link Biztosítások.Biztosítás.Termékgarancia.Szerződés }
             *     
             */
            public Biztosítások.Biztosítás.Termékgarancia.Szerződés getSzerződés() {
                return szerződés;
            }

            /**
             * Sets the value of the szerződés property.
             * 
             * @param value
             *     allowed object is
             *     {@link Biztosítások.Biztosítás.Termékgarancia.Szerződés }
             *     
             */
            public void setSzerződés(Biztosítások.Biztosítás.Termékgarancia.Szerződés value) {
                this.szerződés = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Törlendő" type="{http://promarkvf.hu/ProductTypes}típus_IgenNem"/>
             *         &lt;element name="Számla_sorszáma" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
             *         &lt;element name="Vásárlás_dátuma" type="{http://www.w3.org/2001/XMLSchema}date"/>
             *         &lt;element name="Vásárló">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Név" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
             *                   &lt;element name="Lakcím" type="{http://promarkvf.hu/ProductWS}blokk_Cím"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Vagyontárgy" type="{http://promarkvf.hu/ProductWS}Vagyontárgy"/>
             *         &lt;element name="Biztosítás" type="{http://promarkvf.hu/ProductWS}Biztosítás"/>
             *         &lt;element name="Áruház" type="{http://promarkvf.hu/ProductWS}Áruház"/>
             *         &lt;element name="Eredmény" type="{http://promarkvf.hu/ProductWS}adat_Eredmény"/>
             *         &lt;element name="Hiba" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "t\u00f6rlend\u0151",
                "sz\u00e1mlaSorsz\u00e1ma",
                "v\u00e1s\u00e1rl\u00e1sD\u00e1tuma",
                "v\u00e1s\u00e1rl\u00f3",
                "vagyont\u00e1rgy",
                "biztos\u00edt\u00e1s",
                "\u00e1ruh\u00e1z",
                "eredm\u00e9ny",
                "hiba"
            })
            public static class Szerződés {

                @XmlElement(name = "T\u00f6rlend\u0151", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected String törlendő;
                @XmlElement(name = "Sz\u00e1mla_sorsz\u00e1ma", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected String számlaSorszáma;
                @XmlElement(name = "V\u00e1s\u00e1rl\u00e1s_d\u00e1tuma", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar vásárlásDátuma;
                @XmlElement(name = "V\u00e1s\u00e1rl\u00f3", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló vásárló;
                @XmlElement(name = "Vagyont\u00e1rgy", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected Vagyontárgy vagyontárgy;
                @XmlElement(name = "Biztos\u00edt\u00e1s", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected hu.groupama.portal.product.log.Biztosítás biztosítás;
                @XmlElement(name = "\u00c1ruh\u00e1z", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected Áruház áruház;
                @XmlElement(name = "Eredm\u00e9ny", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected AdatEredmény eredmény;
                @XmlElement(name = "Hiba", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                protected String hiba;

                /**
                 * Gets the value of the törlendő property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTörlendő() {
                    return törlendő;
                }

                /**
                 * Sets the value of the törlendő property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTörlendő(String value) {
                    this.törlendő = value;
                }

                /**
                 * Gets the value of the számlaSorszáma property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSzámlaSorszáma() {
                    return számlaSorszáma;
                }

                /**
                 * Sets the value of the számlaSorszáma property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSzámlaSorszáma(String value) {
                    this.számlaSorszáma = value;
                }

                /**
                 * Gets the value of the vásárlásDátuma property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getVásárlásDátuma() {
                    return vásárlásDátuma;
                }

                /**
                 * Sets the value of the vásárlásDátuma property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setVásárlásDátuma(XMLGregorianCalendar value) {
                    this.vásárlásDátuma = value;
                }

                /**
                 * Gets the value of the vásárló property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló }
                 *     
                 */
                public Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló getVásárló() {
                    return vásárló;
                }

                /**
                 * Sets the value of the vásárló property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló }
                 *     
                 */
                public void setVásárló(Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló value) {
                    this.vásárló = value;
                }

                /**
                 * Gets the value of the vagyontárgy property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Vagyontárgy }
                 *     
                 */
                public Vagyontárgy getVagyontárgy() {
                    return vagyontárgy;
                }

                /**
                 * Sets the value of the vagyontárgy property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Vagyontárgy }
                 *     
                 */
                public void setVagyontárgy(Vagyontárgy value) {
                    this.vagyontárgy = value;
                }

                /**
                 * Gets the value of the biztosítás property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link hu.groupama.portal.product.log.Biztosítás }
                 *     
                 */
                public hu.groupama.portal.product.log.Biztosítás getBiztosítás() {
                    return biztosítás;
                }

                /**
                 * Sets the value of the biztosítás property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link hu.groupama.portal.product.log.Biztosítás }
                 *     
                 */
                public void setBiztosítás(hu.groupama.portal.product.log.Biztosítás value) {
                    this.biztosítás = value;
                }

                /**
                 * Gets the value of the áruház property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Áruház }
                 *     
                 */
                public Áruház getÁruház() {
                    return áruház;
                }

                /**
                 * Sets the value of the áruház property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Áruház }
                 *     
                 */
                public void setÁruház(Áruház value) {
                    this.áruház = value;
                }

                /**
                 * Gets the value of the eredmény property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link AdatEredmény }
                 *     
                 */
                public AdatEredmény getEredmény() {
                    return eredmény;
                }

                /**
                 * Sets the value of the eredmény property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link AdatEredmény }
                 *     
                 */
                public void setEredmény(AdatEredmény value) {
                    this.eredmény = value;
                }

                /**
                 * Gets the value of the hiba property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHiba() {
                    return hiba;
                }

                /**
                 * Sets the value of the hiba property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHiba(String value) {
                    this.hiba = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Név" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
                 *         &lt;element name="Lakcím" type="{http://promarkvf.hu/ProductWS}blokk_Cím"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "n\u00e9v",
                    "lakc\u00edm"
                })
                public static class Vásárló {

                    @XmlElement(name = "N\u00e9v", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                    protected String név;
                    @XmlElement(name = "Lakc\u00edm", namespace = "http://promarkvf.hu/Biztositasok", required = true)
                    protected BlokkCím lakcím;

                    /**
                     * Gets the value of the név property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNév() {
                        return név;
                    }

                    /**
                     * Sets the value of the név property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNév(String value) {
                        this.név = value;
                    }

                    /**
                     * Gets the value of the lakcím property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BlokkCím }
                     *     
                     */
                    public BlokkCím getLakcím() {
                        return lakcím;
                    }

                    /**
                     * Sets the value of the lakcím property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BlokkCím }
                     *     
                     */
                    public void setLakcím(BlokkCím value) {
                        this.lakcím = value;
                    }

                }

            }

        }

    }

}
