//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//


package hu.groupama.portal.product.log;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Biztosítás complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Biztosítás">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Teljes_tartam" type="{http://promarkvf.hu/ProductTypes}típus_Tartam"/>
 *         &lt;element name="Biztosítási_díj" type="{http://promarkvf.hu/ProductTypes}típus_Ft"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Biztos\u00edt\u00e1s", propOrder = {
    "teljesTartam",
    "biztos\u00edt\u00e1siD\u00edj"
})
public class Biztosítás {

    @XmlElement(name = "Teljes_tartam")
    protected int teljesTartam;
    @XmlElement(name = "Biztos\u00edt\u00e1si_d\u00edj")
    protected int biztosításiDíj;

    /**
     * Gets the value of the teljesTartam property.
     * 
     */
    public int getTeljesTartam() {
        return teljesTartam;
    }

    /**
     * Sets the value of the teljesTartam property.
     * 
     */
    public void setTeljesTartam(int value) {
        this.teljesTartam = value;
    }

    /**
     * Gets the value of the biztosításiDíj property.
     * 
     */
    public int getBiztosításiDíj() {
        return biztosításiDíj;
    }

    /**
     * Sets the value of the biztosításiDíj property.
     * 
     */
    public void setBiztosításiDíj(int value) {
        this.biztosításiDíj = value;
    }

}
