//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//


package hu.groupama.portal.product.log;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.groupama.portal.product.log package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.groupama.portal.product.log
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Biztosítások }
     * 
     */
    public Biztosítások createBiztosítások() {
        return new Biztosítások();
    }

    /**
     * Create an instance of {@link Biztosítások.Biztosítás }
     * 
     */
    public Biztosítások.Biztosítás createBiztosításokBiztosítás() {
        return new Biztosítások.Biztosítás();
    }

    /**
     * Create an instance of {@link Biztosítások.Biztosítás.Termékgarancia }
     * 
     */
    public Biztosítások.Biztosítás.Termékgarancia createBiztosításokBiztosításTermékgarancia() {
        return new Biztosítások.Biztosítás.Termékgarancia();
    }

    /**
     * Create an instance of {@link Biztosítások.Biztosítás.Termékgarancia.Szerződés }
     * 
     */
    public Biztosítások.Biztosítás.Termékgarancia.Szerződés createBiztosításokBiztosításTermékgaranciaSzerződés() {
        return new Biztosítások.Biztosítás.Termékgarancia.Szerződés();
    }

    /**
     * Create an instance of {@link BlokkCím }
     * 
     */
    public BlokkCím createBlokkCím() {
        return new BlokkCím();
    }

    /**
     * Create an instance of {@link AdatEredmény }
     * 
     */
    public AdatEredmény createAdatEredmény() {
        return new AdatEredmény();
    }

    /**
     * Create an instance of {@link AdatFelhasználó }
     * 
     */
    public AdatFelhasználó createAdatFelhasználó() {
        return new AdatFelhasználó();
    }

    /**
     * Create an instance of {@link hu.groupama.portal.product.log.Biztosítás }
     * 
     */
    public hu.groupama.portal.product.log.Biztosítás createBiztosítás() {
        return new hu.groupama.portal.product.log.Biztosítás();
    }

    /**
     * Create an instance of {@link Áruház }
     * 
     */
    public Áruház createÁruház() {
        return new Áruház();
    }

    /**
     * Create an instance of {@link Vagyontárgy }
     * 
     */
    public Vagyontárgy createVagyontárgy() {
        return new Vagyontárgy();
    }

    /**
     * Create an instance of {@link Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló }
     * 
     */
    public Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló createBiztosításokBiztosításTermékgaranciaSzerződésVásárló() {
        return new Biztosítások.Biztosítás.Termékgarancia.Szerződés.Vásárló();
    }

}
