//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://promarkvf.hu/ProductWS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.groupama.portal.product.log;
