//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//


package hu.groupama.portal.product.log;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vagyontárgy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vagyontárgy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cikk_kód" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *         &lt;element name="Kategória" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *         &lt;element name="Márka" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *         &lt;element name="Típus" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *         &lt;element name="Gyártói_garancia_hossza" type="{http://promarkvf.hu/ProductTypes}típus_Tartam"/>
 *         &lt;element name="Nagykereskedelmi_ár" type="{http://promarkvf.hu/ProductTypes}típus_Ft"/>
 *         &lt;element name="Fogyasztói_ár" type="{http://promarkvf.hu/ProductTypes}típus_Ft"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vagyont\u00e1rgy", propOrder = {
    "cikkK\u00f3d",
    "kateg\u00f3ria",
    "m\u00e1rka",
    "t\u00edpus",
    "gy\u00e1rt\u00f3iGaranciaHossza",
    "nagykereskedelmi\u00c1r",
    "fogyaszt\u00f3i\u00c1r"
})
public class Vagyontárgy {

    @XmlElement(name = "Cikk_k\u00f3d", required = true)
    protected String cikkKód;
    @XmlElement(name = "Kateg\u00f3ria", required = true)
    protected String kategória;
    @XmlElement(name = "M\u00e1rka", required = true)
    protected String márka;
    @XmlElement(name = "T\u00edpus", required = true)
    protected String típus;
    @XmlElement(name = "Gy\u00e1rt\u00f3i_garancia_hossza")
    protected int gyártóiGaranciaHossza;
    @XmlElement(name = "Nagykereskedelmi_\u00e1r")
    protected int nagykereskedelmiÁr;
    @XmlElement(name = "Fogyaszt\u00f3i_\u00e1r")
    protected int fogyasztóiÁr;

    /**
     * Gets the value of the cikkKód property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCikkKód() {
        return cikkKód;
    }

    /**
     * Sets the value of the cikkKód property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCikkKód(String value) {
        this.cikkKód = value;
    }

    /**
     * Gets the value of the kategória property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKategória() {
        return kategória;
    }

    /**
     * Sets the value of the kategória property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKategória(String value) {
        this.kategória = value;
    }

    /**
     * Gets the value of the márka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMárka() {
        return márka;
    }

    /**
     * Sets the value of the márka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMárka(String value) {
        this.márka = value;
    }

    /**
     * Gets the value of the típus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTípus() {
        return típus;
    }

    /**
     * Sets the value of the típus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTípus(String value) {
        this.típus = value;
    }

    /**
     * Gets the value of the gyártóiGaranciaHossza property.
     * 
     */
    public int getGyártóiGaranciaHossza() {
        return gyártóiGaranciaHossza;
    }

    /**
     * Sets the value of the gyártóiGaranciaHossza property.
     * 
     */
    public void setGyártóiGaranciaHossza(int value) {
        this.gyártóiGaranciaHossza = value;
    }

    /**
     * Gets the value of the nagykereskedelmiÁr property.
     * 
     */
    public int getNagykereskedelmiÁr() {
        return nagykereskedelmiÁr;
    }

    /**
     * Sets the value of the nagykereskedelmiÁr property.
     * 
     */
    public void setNagykereskedelmiÁr(int value) {
        this.nagykereskedelmiÁr = value;
    }

    /**
     * Gets the value of the fogyasztóiÁr property.
     * 
     */
    public int getFogyasztóiÁr() {
        return fogyasztóiÁr;
    }

    /**
     * Sets the value of the fogyasztóiÁr property.
     * 
     */
    public void setFogyasztóiÁr(int value) {
        this.fogyasztóiÁr = value;
    }

}
