//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.24 at 06:40:07 PM CET 
//


package hu.groupama.portal.product.log;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Áruház complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Áruház">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kód" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *         &lt;element name="Név" type="{http://promarkvf.hu/ProductTypes}típus_Kötelező"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u00c1ruh\u00e1z", propOrder = {
    "k\u00f3d",
    "n\u00e9v"
})
public class Áruház {

    @XmlElement(name = "K\u00f3d", required = true)
    protected String kód;
    @XmlElement(name = "N\u00e9v", required = true)
    protected String név;

    /**
     * Gets the value of the kód property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKód() {
        return kód;
    }

    /**
     * Sets the value of the kód property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKód(String value) {
        this.kód = value;
    }

    /**
     * Gets the value of the név property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNév() {
        return név;
    }

    /**
     * Sets the value of the név property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNév(String value) {
        this.név = value;
    }

}
