//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.21 at 10:42:27 AM CET 
//


package hu.groupama.portal.product.setup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adat_Felhasználós complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adat_Felhasználós">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Azonosítós" type="{http://www.promarkvf.hu}típus_Kötelezős"/>
 *         &lt;element name="Piramis_törzsszáms" type="{http://www.promarkvf.hu}típus_Törzsszáms"/>
 *         &lt;element name="Teszt_bejelentkezéss" type="{http://www.promarkvf.hu}típus_IgenNems"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adat_Felhaszn\u00e1l\u00f3s", propOrder = {
    "azonos\u00edt\u00f3s",
    "piramisT\u00f6rzssz\u00e1ms",
    "tesztBejelentkez\u00e9ss"
})
public class AdatFelhasználós {

    @XmlElement(name = "Azonos\u00edt\u00f3s", required = true)
    protected String azonosítós;
    @XmlElement(name = "Piramis_t\u00f6rzssz\u00e1ms", required = true)
    protected String piramisTörzsszáms;
    @XmlElement(name = "Teszt_bejelentkez\u00e9ss", required = true)
    protected String tesztBejelentkezéss;

    /**
     * Gets the value of the azonosítós property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAzonosítós() {
        return azonosítós;
    }

    /**
     * Sets the value of the azonosítós property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAzonosítós(String value) {
        this.azonosítós = value;
    }

    /**
     * Gets the value of the piramisTörzsszáms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiramisTörzsszáms() {
        return piramisTörzsszáms;
    }

    /**
     * Sets the value of the piramisTörzsszáms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiramisTörzsszáms(String value) {
        this.piramisTörzsszáms = value;
    }

    /**
     * Gets the value of the tesztBejelentkezéss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesztBejelentkezéss() {
        return tesztBejelentkezéss;
    }

    /**
     * Sets the value of the tesztBejelentkezéss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesztBejelentkezéss(String value) {
        this.tesztBejelentkezéss = value;
    }

}
