//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.21 at 10:42:27 AM CET 
//


package hu.groupama.portal.product.setup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.groupama.portal.product.setup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Felhasználós_QNAME = new QName("http://www.promarkvf.hu", "Felhaszn\u00e1l\u00f3s");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.groupama.portal.product.setup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdatFelhasználós }
     * 
     */
    public AdatFelhasználós createAdatFelhasználós() {
        return new AdatFelhasználós();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdatFelhasználós }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.promarkvf.hu", name = "Felhaszn\u00e1l\u00f3s")
    public JAXBElement<AdatFelhasználós> createFelhasználós(AdatFelhasználós value) {
        return new JAXBElement<AdatFelhasználós>(_Felhasználós_QNAME, AdatFelhasználós.class, null, value);
    }

}
