//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.21 at 10:42:27 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.promarkvf.hu")
package hu.groupama.portal.product.setup;
